### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by MatthewPaulGithub** [lunakid/external_links_in_new_window#1]
Thanks very much for doing this - the old open links opened up a new screen for every wiki link. This one only opens up for externals, significantly also with the custom menu plugin which many people use.  If you don't mind I will put a comment on the other original plugin, which was good, but may not be what people are looking for - this one is better imho.

Also you should consider registering this in the redmine.org plugins. It's v useful and still an issue at least 3 months ago.

**Comment by xparq** [comment]
Thank you, and sorry that I completely missed your nice comment. (This is not the first case. Either I'm doing something very wrong, or GitHub is not very smart at letting me know if something important (like an issue for my repos) comes up: everything seems to just sink in the noise, if I "watch" other repos.)

> Also you should consider registering this in the redmine.org plugins. It's v useful and still an issue at least 3 months ago.

Good idea, never occurred to me. I'm not actively using Redmine any more, though, so claiming that I "maintain" this would be a false promise, I guess.
